### ISSUE TITLE
add video

### ISSUE THREAD

**Issue by Zz-ww** [Zz-ww/SadTalker-Video-Lip-Sync#1]
https://user-images.githubusercontent.com/52994134/231769817-8196ef1b-c341-41fa-9b6b-63ad0daf14ce.mp4

**Comment by dudupig123** [comment]
hi，作者你好，我感觉上面示例中本算法的口型貌似没有sadTalker准确，本算法看上去更像原来英文的口型，不知道这是不是我的错觉
