### ISSUE TITLE
First run issue

### ISSUE THREAD

**Issue by diegomagikal** [Zz-ww/SadTalker-Video-Lip-Sync#13]
Hi,

I'm trying the first run with no success. After cloning the repository and installing the requirements, I run the following in the main project's directory:

`python inference.py --driven-audio examples/driven_audio/chinese_poem1.wav --source-video examples/driven_video/1.mp4`

The output:

```
Traceback (most recent call last):
  File "M:\AI\SadTalker-Video-Lip-Sync\inference.py", line 5, in <module>
    from src.utils.preprocess import CropAndExtract
ModuleNotFoundError: No module named 'src.utils'

```

I took a look at the project's structure and it's alright (src/utils are there). Am I missing something here? Thanks in advance.

**Comment by Inferencer** [comment]
unsure if this helps but your inference is written wrong you have "-" instead of "_" in a couple of places it should be 
`python inference.py --driven_audio examples/driven_audio/chinese_poem1.wav --source_video examples/driven_video/1.mp4`

**Comment by diegomagikal** [comment]
Hi, thanks for noticing it, but it was a typo. I'm getting the same error if I run that with no parameters: 
`python inference.py`

The output:

```
Traceback (most recent call last):
  File "M:\AI\SadTalker-Video-Lip-Sync\inference.py", line 5, in <module>
    from src.utils.preprocess import CropAndExtract
ModuleNotFoundError: No module named 'src.utils'
```

**Comment by diegomagikal** [comment]
Well, after investigating logs, I noticed an incompatibility between numpy and the Python version I use (3.10). So I installed the 3.8 version, and it works. Thanks.
