### ISSUE TITLE
和VideoReTalking、wav2lip的对比

### ISSUE THREAD

**Issue by wei-kris** [Zz-ww/SadTalker-Video-Lip-Sync#2]
作者可以分享一下SadTalker-Video-Lip-Sync和VideoReTalking、wav2lip的区别吗 ？

**Comment by Zz-ww** [comment]
> 作者可以分享一下SadTalker-Video-Lip-Sync和VideoReTalking、wav2lip的区别吗 ？

已在readme中添加效果对比，以及在sync_show中添加不同方法的合成视频。
