### ISSUE TITLE
 setting an array element with a sequence错误，能解决吗？

### ISSUE THREAD

**Issue by wing158** [Zz-ww/SadTalker-Video-Lip-Sync#23]
3DMM Extraction In Video::   0%|                                                               | 0/135 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "inference.py", line 123, in <module>
    main(args)
  File "inference.py", line 67, in main
    first_coeff_path, crop_pic_path, crop_info = preprocess_model.generate(pic_path, first_frame_dir)
  File "D:\3090\SadTalker-Video-Lip-Sync-master\src\utils\preprocess.py", line 124, in generate
    trans_params, im1, lm1, _ = align_img(frame, lm1, self.lm3d_std)
  File "D:\3090\SadTalker-Video-Lip-Sync-master\src\face3d\util\preprocess.py", line 101, in align_img
    trans_params = np.array([w0, h0, s, t[0], t[1]])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

**Comment by wing158** [comment]
补充，执行的是python inference.py --driven_audio examples\driven_video\chinese_poem1.wav   --source_video   examples\driven_video\1.mp4        --enhancer lip  --use_DAIN --time_step 0.5

**Comment by wing158** [comment]
> 3DMM Extraction In Video:: 0%| | 0/135 [00:00<?, ?it/s] Traceback (most recent call last): File "inference.py", line 123, in main(args) File "inference.py", line 67, in main first_coeff_path, crop_pic_path, crop_info = preprocess_model.generate(pic_path, first_frame_dir) File "D:\3090\SadTalker-Video-Lip-Sync-master\src\utils\preprocess.py", line 124, in generate trans_params, im1, lm1, _ = align_img(frame, lm1, self.lm3d_std) File "D:\3090\SadTalker-Video-Lip-Sync-master\src\face3d\util\preprocess.py", line 101, in align_img trans_params = np.array([w0, h0, s, t[0], t[1]]) ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

**Comment by Chopin68** [comment]
同样的问题。
请问您最后是怎么解决的

**Comment by whitebaby** [comment]
好像安装numpy==1.23.4就行了
