### ISSUE TITLE
莫名其妙就不能用了

### ISSUE THREAD

**Issue by mrhanCH** [Zz-ww/SadTalker-Video-Lip-Sync#31]
在colab上，前几天还好好的，今天又试了下，结果报错不能用了，不知道是哪里的问题，是模型的问题吗？
![image](https://github.com/Zz-ww/SadTalker-Video-Lip-Sync/assets/16829340/18631c2e-a69d-44d4-8395-1024dbf74cb8)

**Comment by littlestone0806** [comment]
face_alignment降级到1.3.4版本，1.3.5不支持2D这个库了

**Comment by mrhanCH** [comment]
> face_alignment降级到1.3.4版本，1.3.5不支持2D这个库了

感谢，我就刚问了AI，确实是这个原因
![image](https://github.com/Zz-ww/SadTalker-Video-Lip-Sync/assets/16829340/15ed765d-b6ec-48bb-9887-d0a755730417)
